feat: running lint on installer objects
replicatedhq/kURL-api pull request #45
Opened 2022-10-17 10:42 UTC by ricardomaraschini

prior to forwarding request to the typescript backend we now pass a lint on the provided installer object.

2022-10-17 11:16 UTC, ricardomaraschini commented on go.mod
> +	github.com/replicatedhq/kurl/kurlkinds v0.0.0-20221016100017-2dbc7eb1506d
@emosbaugh @rrpolanco @laverya would it be the right time for creating a separated repo for `kurlkinds` ? We gonna have to vendor this also in kots-lint repository. What do you reckon ?

2022-10-17 18:15 UTC, emosbaugh requested changes

2022-10-17 18:15 UTC, emosbaugh commented on cmd/server/main.go
> +	r.PathPrefix("/").Handler(&RequestIntercepter{proxy})
would it be better to target the path prefix and method?

```suggestion
	r.PathPrefix("/installer"). Methods("POST").Handler(&RequestIntercepter{proxy})
	r.PathPrefix("/").Handler(proxy)
```

2022-10-18 08:31 UTC, ricardomaraschini commented on cmd/server/main.go
> +		r.Body = io.NopCloser(preserved)
There is no need for that on the server side. I double checked and there is no leaking file descriptor.

2022-10-18 13:12 UTC, emosbaugh commented on cmd/server/main.go
> +		r.Body = io.NopCloser(preserved)
How did you double check? What is the drawback to closing?

2022-10-19 09:15 UTC, ricardomaraschini commented on cmd/server/main.go
> +		r.Body = io.NopCloser(preserved)
For sake of completeness: I have double checked by inspected the `/proc/<pid>/fd` directory while doing multiple simultaneous requests. 

That said, as we agreed in our call I have added the `Close()` call as it does not bring us any drawback.

2022-10-19 13:50 UTC, emosbaugh requested changes

2022-10-19 13:50 UTC, emosbaugh commented on cmd/server/main.go
> +		r.Body = io.NopCloser(bytes.NewReader(body))
Can you explicitly close the body one line above this line before r.Body is overwritten? I didn't try it out but that defer may be closing the overwritten body.

2022-10-19 14:59 UTC, emosbaugh approved these changes

2022-10-20 14:40 UTC, merged